from __future__ import annotations
import pandas as pd
from datetime import datetime

STYLE = """
<style>
body { font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin: 24px; }
h1 { font-size: 22px; }
.table { border-collapse: collapse; width: 100%; margin: 16px 0; font-size: 14px; }
.table th, .table td { border: 1px solid #ddd; padding: 8px; text-align: right; }
.table th { background: #f4f4f4; text-align: center; }
.table td:first-child, .table th:first-child { text-align: left; }
.badge { display: inline-block; padding: 2px 8px; border-radius: 12px; background: #eee; margin-left: 8px; font-size: 12px; }
small { color: #666; }
</style>
"""

def _html_table(df: pd.DataFrame, title: str) -> str:
    if df is None or df.empty:
        return f"<h2>{title}</h2><p><em>No data.</em></p>"
    return (
        f"<h2>{title}</h2>"
        + df.to_html(classes=["table"], index=False, border=0, justify="center")
    )

def build_html_report(title: str, etf_metrics: pd.DataFrame, bit2me_balances: pd.DataFrame | None = None) -> str:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    parts = [
        "<html><head><meta charset='utf-8'>",
        STYLE,
        f"<title>{title}</title></head><body>",
        f"<h1>{title} <span class='badge'>{ts}</span></h1>",
        _html_table(etf_metrics, "ETF — Volatility & Daily Change"),
        _html_table(bit2me_balances, "Bit2Me — Balances"),
        "<p><small>Auto-generated by bit2me-etf-tracker.</small></p>",
        "</body></html>",
    ]
    return "".join(parts)
